// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVpj24qoRohgObGMlcpqiDU9V-dBepd4s',
    appId: '1:744971965093:web:d3efaa0f9ae09261e8f34c',
    messagingSenderId: '744971965093',
    projectId: 'digitend-79f63',
    authDomain: 'digitend-79f63.firebaseapp.com',
    storageBucket: 'digitend-79f63.firebasestorage.app',
    measurementId: 'G-WGVFQ3G3J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQKyrcSh8jYtunu6MIvRX2opowar5RaQ',
    appId: '1:744971965093:android:b725db1f1c5d1fc3e8f34c',
    messagingSenderId: '744971965093',
    projectId: 'digitend-79f63',
    storageBucket: 'digitend-79f63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmMPG1s7Jk_6XQFqiVuhyAGO29-FswsI',
    appId: '1:744971965093:ios:422fb26a64a96ef1e8f34c',
    messagingSenderId: '744971965093',
    projectId: 'digitend-79f63',
    storageBucket: 'digitend-79f63.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
